routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('messages','MessagesController');
Route::resource('likes','likesController');

Route::get('message/like/{id}', ['as' => 'message.like', 'uses' => 'LikesController@likeMessage']);

Route::get('login/facebook', 'Auth\LoginController@redirectToProvider');
Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderCallback');

app/Message.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Message extends Model
{
    //
    protected $fillable  = [
    	'titre',
    	'description',
    	'user_id',
    	'like',
        'file',
    	
    ];

    public function user(){
    	return $this->belongsto('App\User');
    }

    public function likes()
    {
        return $this->hasMany('App\like');
    }

    
}

app/Http/Controllers/MessagesController.php
<?php

namespace App\Http\Controllers;

use App\Message;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Input;
use Illuminate\Support\Facades\Storage;

class MessagesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        if (Auth::check()) {
          
        $messages = Message::all();

        return view('messages.index',['messages'=>$messages]);
        }
        return view('auth.login');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('messages.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        if (Auth::check()) {
            
            Storage::putFileAs('public',$request->file('file'),$request->file('file')->getClientOriginalName());
            $message = message::create([

                'titre'=> $request->input('titre'),
                'description'=> $request->input('description'),
                'user_id'=> Auth::user()->id,
                'file'=> $request->file('file')->getClientOriginalName(),
                ]);

        if ($message) {


            return redirect()->route('messages.index', ['message'=> $message->id])->with('success','tweet created successfully');
        }
        }
         return back()->withinput()->with('errors','you should be connected'); 
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Message  $message
     * @return \Illuminate\Http\Response
     */
    public function show(Message $message)
    {
        //
        
    }
    

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Message  $message
     * @return \Illuminate\Http\Response
     */
    public function edit(Message $message)
    {
        //
        $message = Message::find($message->id);
        
        return view('messages.edit',['message'=> $message]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Message  $message
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Message $message)
    {
        Storage::putFileAs('public',$request->file('file'),$request->file('file')->getClientOriginalName());
         $messageUpdate = message::where('id',$message->id)->update([
            'titre'=>$request->input('titre'),
            'description'=>$request->input('description'),
            'file'=>$request->file('file')->getClientOriginalName(),

            ]);
        if($messageUpdate){
            return redirect()->route('messages.index',['message'=>$message->id])->with('success','message update successfully');
        }

        //redirect
        return back()->withinput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Message  $message
     * @return \Illuminate\Http\Response
     */
    public function destroy(Message $message)
    {
        //
         $findmessage = Message::find($message->id);
        if ($findmessage->delete()) {
            return redirect()->route('messages.index')->with('success','message deleted successfully');
        }
        return back()->withinput()->with('error','message could not be deleted');
    }

    public function postLikePost(Request $request)
    {
        $post_id = $request['postId'];
        $is_like = $request['isLike'] === 'true';
        $update = false;
        $post = Post::find($post_id);
        if (!$post) {
            return null;
        }
        $user = Auth::user();
        $like = $user->likes()->where('post_id', $post_id)->first();
        if ($like) {
            $already_like = $like->like;
            $update = true;
            if ($already_like == $is_like) {
                $like->delete();
                return null;
            }
        } else {
            $like = new Like();
        }
        $like->like = $is_like;
        $like->user_id = $user->id;
        $like->post_id = $post->id;
        if ($update) {
            $like->update();
        } else {
            $like->save();
        }
        return null;
    }
}

resources/views/messages/Create.blade.php
@extends('layouts/app')

@section('content')

<div class="row col-md-9 col-lg-9 col-sm-9 pull-left " style="background: white;">
<h1>Create Message </h1>

      <!-- Example row of columns -->
      <div class="row  col-md-12 col-lg-12 col-sm-12" >

      <form method="post" enctype="multipart/form-data" action="{{ route('messages.store') }}">
                            {{ csrf_field() }}

                            <div class="form-group">
                                <label for="company-name">Name<span class="required">*</span></label>
                                <input   placeholder="Enter titre"  
                                          id="message-titre"
                                          required
                                          name="titre"
                                          spellcheck="false"
                                          class="form-control"
                                          
                                           />
                            </div>


                            <div class="form-group">
                                <label for="company-content">Description</label>
                                <textarea placeholder="Enter description" 
                                          style="resize: vertical" 
                                          id="company-content"
                                          required
                                          name="description"
                                          rows="5" spellcheck="false"
                                          class="form-control autosize-target text-left">
                                         
                                </textarea>
                            </div>
                            <div class="form-group">
                                <label for="company-content">File</label>
                                <input type="file" name="file" required>
                            </div>
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary"
                                       value="Submit"/>
                            </div>
                        </form>
   

      </div>
</div>


<div class="col-sm-3 col-md-3 col-lg-3 pull-right">
          <!--<div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div> -->
          <div class="sidebar-module">
            <h4>Actions</h4>
            <ol class="list-unstyled">
              
              <li><a href="/messages"><i class="fa fa-building" aria-hidden="true"></i> All messages</a></li>
              
            </ol>
          </div>

          <!--<div class="sidebar-module">
            <h4>Members</h4>
            <ol class="list-unstyled">
              <li><a href="#">March 2014</a></li>
            </ol>
          </div> -->
</div>
        
@endsection

resources/views/messages/edit.blade.php
@extends('layouts/app')

@section('content')

<div class="row col-md-9 col-lg-9 col-sm-9 pull-left " style="background: white;">
<h1>Update Tweet </h1>

      <!-- Example row of columns -->
      <div class="row  col-md-12 col-lg-12 col-sm-12" >

      <form method="post" enctype="multipart/form-data" action="{{ route('messages.update',[$message->id]) }}">
                            {{ csrf_field() }}

                            <input type="hidden" name="_method" value="put">

                            <div class="form-group">
                                <label for="message-titre">Titre<span class="required">*</span></label>
                                <input   placeholder="Enter Titre"  
                                          id="message-titre"
                                          required
                                          name="titre"
                                          spellcheck="false"
                                          class="form-control"
                                          value="{{ $message->titre }}"
                                           />
                            </div>


                            <div class="form-group">
                                <label for="company-content">Description</label>
                                <textarea placeholder="Enter description" 
                                          style="resize: vertical" 
                                          id="message-content"
                                          name="description"
                                          rows="5" spellcheck="false"
                                          class="form-control autosize-target text-left">
                                          {{ $message->description }}</textarea>
                            </div>
                            <div class="form-group">
                                <label for="company-content">File</label>
                                <input type="file" name="file" required>
                            </div>
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary"
                                       value="Submit"/>
                            </div>
                        </form>
   

      </div>
</div>


<div class="col-sm-3 col-md-3 col-lg-3 pull-right">
          <!--<div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div> -->
          <div class="sidebar-module">
            <h4>Actions</h4>
            <ol class="list-unstyled">
              
              <li><a href="/messages"><i class="fa fa-building" aria-hidden="true"></i> All messages</a></li>
              
            </ol>
          </div>

          <!--<div class="sidebar-module">
            <h4>Members</h4>
            <ol class="list-unstyled">
              <li><a href="#">March 2014</a></li>
            </ol>
          </div> -->
</div>
        
@endsection

resources/views/messages/index.blade.php
@extends('layouts.app')

@section('content')
<div class="col-md-6 col-lg-6 col-md-offset-3  col-lg-offset-3">
    <div class="panel panel-primary ">
  <div class="panel-heading">Messsages<a class="pull-right" href="/messages/create"  style="color: black ">Ajouter</a></div> 
  <div class="panel-body">
    <ul class="list-group">

 		@foreach($messages as $message)
          <!-- Title -->
          	
         			 <div class="comment-box">
						<div class="comment-head">
							<h6 class="comment-name by-author"><a href="#">{{$message->user->name}}</a></h6>
						</div>
             <label>Titre : {{$message->titre}}</label> 
						<div class="comment-content">
							{{$message->description}}
						</div>
            <div class="comment-content">
               <a href="{{url('/')}}{{ Storage::disk('local')->url($message->file)}}">File : {{$message->file}}</a>
            </div>
						
					 <!--<label style="color: blue">{{$message->total}}  <i class="far fa-thumbs-up"></i></label>&nbsp;&nbsp;
           
           @if( $message->user->name == 'ayoub' )
           <a href="#">like</a>
           @endif-->

					 <span >  on {{$message->created_at}}</span> 

           @if( Auth::user()->id == $message->user_id)
					 <a   
              href="{{ route('messages.destroy',[$message->id]) }}"
                  onclick="
                  var result = confirm('Are you sure you wish to delete this message?');
                      if( result ){
                              event.preventDefault();
                              document.getElementById('delete-form').submit();
                      }
                          "
                          >
                  Delete
              </a>
              <a href="/messages/{{$message->id}}/edit">Edit</a>
              @endif
              <form id="delete-form" action="{{ route('messages.destroy',[$message->id]) }}" 
                method="POST" style="display: none;">
                        <input type="hidden" name="_method" value="delete">
                        {{ csrf_field() }}
              </form>
					<hr>
					</div>

		@endforeach


</ul>
  </div>
</div>
</div>

@endsection